# Site settings
title: bekiipsum.com
email: overlord@archon-digital.com
description: "Ang bukod-tanging dummy text generator ng mga Beki. Ito and Bekiipsum.com - Lorem ipsum keme keme."
baseurl: ""
url: "http://bekiipsum.com"
username: bekiipsum
timezone: Asia/Manila
paginate: 8
paginate_path: "articles/:num"

# Build settings
markdown: kramdown
permalink: pretty

gems:
- jekyll-redirect-from
- jekyll-paginate
#   - jekyll-sitemap